const express = require('express');
const doctorRepository = require('../repositories/doctorRepository');
const appointmentService = require('../services/appointmentService');
const { ensureDatabase } = require('../db/state');

const router = express.Router();
const slots = ['09:00:00', '10:30:00', '12:00:00', '14:00:00', '15:30:00', '17:00:00'];
const today = () => new Date().toISOString().slice(0, 10);
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);

function layout(content) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#12324a"><title>CareBridge Hospital</title><style>
:root{--navy:#12324a;--navy-2:#1d4963;--teal:#168b83;--teal-dark:#0d6d67;--mint:#dff4ef;--mint-soft:#f3faf8;--coral:#f28c70;--ink:#173042;--muted:#687b84;--line:#dbe8e5;--white:#fff;--shadow:0 24px 70px rgba(18,50,74,.13)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f7faf9;color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body>header{height:80px;padding:0 max(24px,6vw);display:flex;align-items:center;justify-content:space-between;background:rgba(255,255,255,.94);border-bottom:1px solid rgba(219,232,229,.8);position:relative;z-index:5}.brand{display:flex;align-items:center;color:var(--navy);font-size:20px;font-weight:850;letter-spacing:-.02em}.brand b{display:inline-grid;place-items:center;width:40px;height:40px;margin-right:11px;border-radius:13px;background:var(--teal);box-shadow:0 8px 20px rgba(22,139,131,.22);color:#fff;font-size:24px}.header-note{display:flex;align-items:center;gap:8px;color:var(--navy-2);font-size:12px;font-weight:750}.header-note:before{content:"";width:8px;height:8px;border-radius:50%;background:#58b68e;box-shadow:0 0 0 4px #e4f5ec}
.hero{overflow:hidden;padding:68px 24px 128px;background:radial-gradient(circle at 8% 0,#fff 0,transparent 30%),linear-gradient(135deg,#effaf7 0,#e4f3f2 58%,#dceff0 100%)}.hero-inner{max-width:1120px;margin:auto;display:grid;grid-template-columns:.9fr 1.1fr;align-items:center;gap:64px}.hero-copy{text-align:left}.eyebrow{display:inline-flex;align-items:center;gap:8px;color:var(--teal-dark);font-size:11px;font-weight:850;letter-spacing:.14em;text-transform:uppercase}.eyebrow:before{content:"";width:24px;height:2px;background:var(--coral)}h1{max-width:780px;margin:14px auto 18px;color:var(--navy);font-size:clamp(42px,6vw,70px);line-height:.98;letter-spacing:-.055em}.hero h1{margin-left:0}.hero p{max-width:540px;margin:0;color:var(--muted);font-size:17px;line-height:1.7}.hero-points{display:flex;gap:20px;margin-top:28px;color:var(--navy-2);font-size:12px;font-weight:750}.hero-points span:before{content:"✓";display:inline-grid;place-items:center;width:20px;height:20px;margin-right:7px;border-radius:50%;background:#fff;color:var(--teal);box-shadow:0 5px 15px rgba(18,50,74,.08)}.hero-visual{position:relative}.hero-visual:before{content:"";position:absolute;inset:10% -8% -8% 16%;border-radius:40px;background:var(--coral);opacity:.18;transform:rotate(4deg)}.hero-art{position:relative;display:block;width:100%;border:8px solid rgba(255,255,255,.78);border-radius:34px;box-shadow:0 30px 65px rgba(18,50,74,.2);aspect-ratio:4/3;object-fit:cover}
.shell{max-width:1120px;margin:-74px auto 80px;padding:0 24px;position:relative}.trust{display:grid;grid-template-columns:repeat(3,1fr);margin-bottom:22px;padding:18px 26px;border:1px solid rgba(219,232,229,.85);border-radius:18px;background:rgba(255,255,255,.94);box-shadow:0 12px 35px rgba(18,50,74,.08);backdrop-filter:blur(10px)}.trust div{padding:4px 22px;border-right:1px solid var(--line)}.trust div:last-child{border:0}.trust strong{display:block;color:var(--navy);font-size:20px}.trust span{color:var(--muted);font-size:12px}
.card{padding:40px;border:1px solid rgba(219,232,229,.8);border-radius:28px;background:#fff;box-shadow:var(--shadow)}.section-kicker{margin-bottom:8px;color:var(--teal);font-size:11px;font-weight:850;letter-spacing:.13em;text-transform:uppercase}.card h2{margin:0 0 7px;color:var(--navy);font-size:28px;letter-spacing:-.025em}.card>p{margin:0 0 30px;color:var(--muted)}.form{display:grid;gap:20px}.two{display:grid;grid-template-columns:1fr 1fr;gap:18px}label{display:grid;gap:8px;color:var(--navy-2);font-size:11px;font-weight:800;letter-spacing:.06em;text-transform:uppercase}input,select,textarea{width:100%;padding:15px 16px;border:1px solid var(--line);border-radius:12px;background:#fbfdfc;color:var(--ink);font:inherit;outline:0;transition:.2s}textarea{resize:vertical}input:hover,select:hover,textarea:hover{border-color:#b8d1cc}input:focus,select:focus,textarea:focus{border-color:var(--teal);box-shadow:0 0 0 4px rgba(22,139,131,.11);background:#fff}button,.button{display:inline-flex;align-items:center;justify-content:center;padding:16px 24px;border:0;border-radius:13px;background:var(--teal);box-shadow:0 10px 24px rgba(22,139,131,.2);color:#fff;font-weight:800;text-decoration:none;cursor:pointer;transition:.2s}button:hover,.button:hover{background:var(--teal-dark);transform:translateY(-1px)}.alert{margin-bottom:20px;padding:14px 16px;border-left:4px solid var(--coral);border-radius:10px;background:#fff3ef;color:#9b4937;font-size:13px}
.doctors{margin-top:82px}.section-heading{max-width:590px;margin:auto;text-align:center}.section-heading h2{margin:8px 0;color:var(--navy);font-size:34px;letter-spacing:-.03em}.section-heading p{margin:0;color:var(--muted);line-height:1.6}.doctor-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:30px}.doctor{position:relative;overflow:hidden;padding:24px;border:1px solid var(--line);border-radius:20px;background:#fff;transition:.25s}.doctor:before{content:"";position:absolute;top:0;left:0;width:100%;height:4px;background:linear-gradient(90deg,var(--teal),#6bbeb3)}.doctor:hover{transform:translateY(-4px);border-color:#bcd8d3;box-shadow:0 18px 38px rgba(18,50,74,.1)}.doctor-icon{display:grid;place-items:center;width:42px;height:42px;margin-bottom:18px;border-radius:13px;background:var(--mint);color:var(--teal);font-size:19px;font-weight:900}.doctor span{color:var(--teal-dark);font-size:10px;font-weight:850;letter-spacing:.08em;text-transform:uppercase}.doctor h3{margin:8px 0 4px;color:var(--navy)}.doctor p{margin:0;color:var(--muted);font-size:12px;line-height:1.55}.doctor b{display:block;margin-top:16px;color:var(--navy)}.doctor b small{color:var(--muted);font-weight:500}
.success{max-width:780px;margin:70px auto;padding:0 20px;text-align:center}.check{width:68px;height:68px;display:grid;place-items:center;margin:0 auto 18px;border-radius:50%;background:var(--teal);box-shadow:0 12px 28px rgba(22,139,131,.22);color:#fff;font-size:30px}.success>h1{font-size:clamp(40px,6vw,60px)}.success>p{color:var(--muted)}.ticket{margin:35px 0;padding:32px;border:1px solid var(--line);border-radius:24px;background:#fff;box-shadow:var(--shadow);text-align:left}.ticket header{height:auto;padding:0 0 20px;border-bottom:1px dashed #b9cbc7}.ticket-grid{display:grid;grid-template-columns:1fr 1fr;gap:28px;padding:28px 0}.ticket small{color:var(--muted);font-size:10px;font-weight:800;letter-spacing:.1em}.ticket h3{margin:5px 0;color:var(--navy)}.ticket p{margin:4px 0;color:var(--muted)}.ticket footer{display:flex;justify-content:space-between;padding-top:19px;border-top:1px solid var(--line)}.status{padding:6px 10px;border-radius:999px;background:var(--mint);color:var(--teal-dark);font-size:11px;font-weight:850}.error-page{max-width:700px;margin:100px auto;padding:30px;text-align:center}.error-page h1{font-size:38px}
@media(max-width:800px){body>header{height:70px}.header-note{display:none}.hero{padding-top:48px}.hero-inner{grid-template-columns:1fr;gap:38px}.hero-copy{text-align:center}.hero h1,.hero p{margin-left:auto;margin-right:auto}.hero-points{justify-content:center}.hero-visual{max-width:600px;margin:auto}.trust{grid-template-columns:1fr}.trust div{padding:12px;border-right:0;border-bottom:1px solid var(--line);text-align:center}.two,.doctor-grid,.ticket-grid{grid-template-columns:1fr}.card{padding:26px}.ticket footer{display:grid;gap:8px}}@media(max-width:480px){.hero{padding-left:18px;padding-right:18px}.hero-points{display:grid;gap:10px}.shell{padding:0 14px}.card{border-radius:22px}.hero-art{border-width:5px;border-radius:24px}}
</style></head><body><header><div class="brand"><b>+</b>CareBridge</div><span class="header-note">Appointments available today</span></header>${content}</body></html>`;
}

async function homePage(error = '', form = {}) {
  await ensureDatabase();
  const doctors = await doctorRepository.getDoctors();
  const options = doctors.map((doctor) => `<option value="${doctor.id}" ${String(form.doctorId) === String(doctor.id) ? 'selected' : ''}>${escapeHtml(doctor.name)} — ${escapeHtml(doctor.specialty)}</option>`).join('');
  const slotOptions = slots.map((slot) => `<option value="${slot}" ${form.time === slot ? 'selected' : ''}>${new Date(`2000-01-01T${slot}Z`).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', timeZone: 'UTC' })}</option>`).join('');
  const doctorCards = doctors.map((doctor) => `<article class="doctor"><div class="doctor-icon">+</div><span>${escapeHtml(doctor.specialty)}</span><h3>${escapeHtml(doctor.name)}</h3><p>${escapeHtml(doctor.qualification)} · ${doctor.experience_years}+ years</p><b>₹${doctor.consultation_fee} <small>consultation</small></b></article>`).join('');
  return layout(`<section class="hero"><div class="hero-inner"><div class="hero-copy"><span class="eyebrow">Care made simple</span><h1>Better care starts with the right conversation.</h1><p>Connect with trusted specialists and schedule your hospital visit in just a few simple steps.</p><div class="hero-points"><span>Verified specialists</span><span>Secure booking</span></div></div><div class="hero-visual"><img class="hero-art" src="/images/care-consultation.png" alt="A CareBridge doctor consulting with a patient" width="724" height="543"></div></div></section><main class="shell"><section class="trust" aria-label="CareBridge highlights"><div><strong>6 specialties</strong><span>Expert care for every need</span></div><div><strong>Same-day slots</strong><span>Flexible appointment times</span></div><div><strong>Simple & secure</strong><span>Book with confidence</span></div></section><section class="card"><div class="section-kicker">Book your visit</div><h2>Schedule an appointment</h2><p>Tell us what you need and we’ll reserve your preferred time.</p>${error ? `<div class="alert">${escapeHtml(error)}</div>` : ''}<form class="form" method="post" action="/appointments/book"><label>Choose doctor<select name="doctorId" required><option value="">Select a specialist</option>${options}</select></label><div class="two"><label>Patient name<input name="name" value="${escapeHtml(form.name)}" maxlength="100" placeholder="Your full name" required></label><label>Phone number<input name="phone" value="${escapeHtml(form.phone)}" maxlength="30" placeholder="+91 98765 43210" required></label></div><label>Email address<input type="email" name="email" value="${escapeHtml(form.email)}" maxlength="160" placeholder="you@example.com" required></label><div class="two"><label>Appointment date<input type="date" name="date" min="${today()}" value="${escapeHtml(form.date || today())}" required></label><label>Available time<select name="time" required>${slotOptions}</select></label></div><label>Reason for visit<textarea name="reason" rows="4" maxlength="500" placeholder="Briefly tell the doctor how they can help" required>${escapeHtml(form.reason)}</textarea></label><button type="submit">Confirm my appointment →</button></form></section><section class="doctors"><div class="section-heading"><span class="eyebrow">Meet your care team</span><h2>Experienced specialists, here for you</h2><p>Choose from our trusted team of doctors across six areas of care.</p></div><div class="doctor-grid">${doctorCards}</div></section></main>`);
}

router.get('/', async (request, response, next) => {
  try { response.type('html').send(await homePage()); } catch (error) { next(error); }
});

router.post('/appointments/book', async (request, response, next) => {
  const form = request.body;
  const doctorId = Number(form.doctorId);
  const valid = Number.isInteger(doctorId) && doctorId > 0 && form.name?.trim().length >= 2 && /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(form.email || '') && /^[+0-9 ()-]{7,30}$/.test(form.phone || '') && form.date >= today() && slots.includes(form.time) && form.reason?.trim().length >= 5;
  if (!valid) return response.status(400).type('html').send(await homePage('Please complete every field with valid information.', form));
  try {
    const doctor = await doctorRepository.getDoctor(doctorId);
    if (!doctor) return response.status(404).type('html').send(await homePage('The selected doctor is unavailable.', form));
    const reference = await appointmentService.createAppointment({ doctorId, name: form.name.trim(), email: form.email.trim().toLowerCase(), phone: form.phone.trim(), date: form.date, time: form.time, reason: form.reason.trim() });
    return response.redirect(`/appointments/${reference}`);
  } catch (error) {
    if (error.status === 409) return response.status(409).type('html').send(await homePage(error.message, form));
    return next(error);
  }
});

router.get('/appointments/:reference', async (request, response, next) => {
  try {
    const appointment = await appointmentService.getAppointment(request.params.reference);
    if (!appointment) return response.status(404).type('html').send(layout('<section class="error-page"><h1>Appointment not found</h1><a class="button" href="/">Return home</a></section>'));
    return response.type('html').send(layout(`<main class="success"><div class="check">✓</div><span class="eyebrow">Appointment confirmed</span><h1>You’re all set.</h1><p>Your appointment is saved in MySQL.</p><article class="ticket"><header><div><small>REFERENCE</small><h3>${escapeHtml(appointment.reference_code)}</h3></div><span class="status">${escapeHtml(appointment.status)}</span></header><div class="ticket-grid"><div><small>DOCTOR</small><h3>${escapeHtml(appointment.doctor_name)}</h3><p>${escapeHtml(appointment.specialty)}</p></div><div><small>DATE & TIME</small><h3>${escapeHtml(appointment.appointment_date)}</h3><p>${escapeHtml(String(appointment.appointment_time).slice(0, 5))}</p></div><div><small>PATIENT</small><h3>${escapeHtml(appointment.patient_name)}</h3><p>${escapeHtml(appointment.patient_email)}</p></div><div><small>REASON</small><p>${escapeHtml(appointment.reason)}</p></div></div><footer><span>Consultation fee</span><strong>₹${appointment.consultation_fee}</strong></footer></article><a class="button" href="/">Book another appointment</a></main>`));
  } catch (error) { return next(error); }
});

module.exports = router;
